server:
  port: 9999
  servlet:
    context-path: /rest
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uc?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml #需要扫描到相应的xml文件


